# permissions for end users to view operations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: operation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: operation-viewer-role
rules:
- apiGroups:
  - core.polyaxon.com
  resources:
  - operations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.polyaxon.com
  resources:
  - operations/status
  verbs:
  - get
