name: mloperator

on: [push, pull_request]

jobs:
  operator:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1
    - uses: actions/checkout@v2.4.0
    - uses: helm/kind-action@v1.2.0
    - name: test
      env:
        KUBEBUILDER_CONTROLPLANE_START_TIMEOUT: 600s
      run: |
        OS=$(go env GOOS)
        ARCH=$(go env GOARCH)
        KUBEBUILDER_VERSION=3.2.0
        # download kubebuilder and extract it to tmp
        curl -L -o /tmp/kubebuilder https://go.kubebuilder.io/dl/latest/${OS}/${ARCH}
        sudo mv /tmp/kubebuilder /usr/local/kubebuilder
        export PATH=$PATH:/usr/local/kubebuilder/bin
        go version
        go install
        make test
